### ISSUE TITLE
External paths

### ISSUE THREAD

**Issue by nvanva** [FrancescoPeriti/CSSDetection#1]
Hello! When running ```run_comparison.sh``` for DWUG Ru ```model_evaluation.py``` fails because of the reference to ```/mimer/NOBACKUP/groups/cik_data/rqlsc/dwug_ru12/stats/stats_groupings.csv```. Where can I take this file? Is it the file ```dwug_ru12/stats/stats_groupings.csv``` from the dataset or somehow modified version of this file?
```
Traceback (most recent call last):                                                                                                                           
  File "/localscratch/12732071/CSSDetection/src/model_evaluation.py", line 312, in <module>                                                                  
    dfs, gold_wic_dfs, gold_wsi_dfs, gold_lsc_df = read_data(benchmark, model, layer, wsi=wsi_lsc)                                                           
  File "/localscratch/12732071/CSSDetection/src/model_evaluation.py", line 125, in read_data                                                                 
    gold_lsc_df = load_gold_lsc(benchmark)[['lemma', 'change_graded']]                                                                                       
  File "/localscratch/12732071/CSSDetection/src/model_evaluation.py", line 38, in load_gold_lsc                                                              
    df = pd.read_csv(f'/mimer/NOBACKUP/groups/cik_data/rqlsc/{benchmark}/stats/stats_groupings.csv', sep='\t')                                               
  File "/localscratch/12732071/venv/lib64/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)                                                                                                                             
  File "/localscratch/12732071/venv/lib64/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/localscratch/12732071/venv/lib64/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/localscratch/12732071/venv/lib64/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/localscratch/12732071/venv/lib64/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/localscratch/12732071/venv/lib64/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/mimer/NOBACKUP/groups/cik_data/rqlsc/dwug_ru12/stats/stats_groupings.csv'
```

**Comment by FrancescoPeriti** [comment]
Hi, yes, `dwug_ru12/stats/stats_groupings.csv` is the correct file. Thanks for reaching out to us. We forgot to remove the absolute path. The original data we are referring to can be downloaded from here: https://github.com/akutuzov/rushifteval_public/tree/main/durel/rushifteval1/stats
